# Generated by Django 5.0.6 on 2024-06-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ehospital_app', '0002_doctorrecommondation_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorrecommondation',
            name='symptmId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
