# Generated by Django 5.0.6 on 2024-06-03 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ehospital_app', '0003_doctorrecommondation_symptmid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorrecommondation',
            old_name='selected',
            new_name='selected_symptoms',
        ),
    ]
