# Generated by Django 5.0.6 on 2024-06-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ehospital_app', '0004_rename_selected_doctorrecommondation_selected_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorrecommondation',
            name='patent_Id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
