# Generated by Django 5.0.6 on 2024-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ehospital_app', '0005_doctorrecommondation_patent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorrecommondation',
            name='recommended_doctor',
        ),
        migrations.AddField(
            model_name='doctorrecommondation',
            name='recommended_doctor',
            field=models.ManyToManyField(blank=True, to='Ehospital_app.doctor'),
        ),
    ]
