# Generated by Django 5.0.6 on 2024-06-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ehospital_app', '0006_remove_doctorrecommondation_recommended_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Symptom',
        ),
        migrations.AddField(
            model_name='symptomm',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
