# Generated by Django 5.0.6 on 2024-06-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ehospital_app', '0007_delete_symptom_symptomm_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Symptomm',
            new_name='Symptom',
        ),
    ]
