# Generated by Django 5.0.6 on 2024-06-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ehospital_app', '0010_pharmacistrequestpayment_hospitalname'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_discharged',
            field=models.BooleanField(default=False),
        ),
    ]
