# Generated by Django 5.0.6 on 2024-06-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ehospital_app', '0012_remove_patient_is_discharged'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_discharged',
            field=models.BooleanField(default=False),
        ),
    ]
